name: custom_textfield_with_countrycode
description: "Custom TextFormField with country code picker, password visibility toggle, and extensive customization options."
version: 0.0.4
homepage: https://github.com/karthikerebs/custom_textfield_with_countrycode.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  country_code_picker: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
